### ISSUE TITLE
Проблема с кодировкой при добавлении филиала

### ISSUE THREAD

**Issue by maxim4** [akshinmustafayev/Printer-Setup-System-Remastered#2]
При добавлении филиала на русском языке в базу пишется с неправильной кодировкой, и на сайте отображается с неверной кодировкой. Если в базу добавить филиал руками, то отображается правильно.

![изображение](https://user-images.githubusercontent.com/7742713/112139075-53aff200-8ba0-11eb-9f4a-2746a2215562.png)

CentOS Linux release 8.3.2011
mariadb.x86_64     3:10.3.27-3
Tomcat       8.5.64

**Comment by akshinmustafayev** [comment]
Пофикшено.
Задеплойте новый WAR с [релиза](https://github.com/akshinmustafayev/Printer-Setup-System-Remastered/releases/download/1.0.0/PrinterSetupSystem.war)

**Comment by drdethbsd** [comment]
Спасибо, помогло

**Comment by akshinmustafayev** [comment]
Вам спасибо!
