### ISSUE TITLE
Printer creation error!

### ISSUE THREAD

**Issue by dsm150** [akshinmustafayev/Printer-Setup-System-Remastered#3]
Здравствуйте.
Пробую создать принтер, заполняю все поля, при сохранении - Printer creation error!
Как бы понять, почему возникает эта ошибка?

**Comment by akshinmustafayev** [comment]
Добрый день.
Посмотрите логи tomcat и SQL запрос приходящий в mysql. Попробуйте выполнить SQL запросиз логов вручную. БД должна быть 10.4.11-MariaDB.

**Comment by dsm150** [comment]
Благодарю!
Я использовал mysql server, с mariadb все заработало.
Буду пробовать применять в бою 🙏🏻

**Comment by akshinmustafayev** [comment]
Не за что. Спасибо за то что используете мое приложение.
